# Semgrep Security Rules for YouLab
# These rules detect common Python security vulnerabilities
# Docs: https://semgrep.dev/docs/writing-rules/rule-syntax

rules:
  # === INJECTION VULNERABILITIES ===

  - id: python-sql-injection
    patterns:
      - pattern-either:
          - pattern: $CURSOR.execute($QUERY + ...)
          - pattern: $CURSOR.execute(f"...")
          - pattern: $CURSOR.execute("..." % ...)
          - pattern: $CURSOR.executemany($QUERY + ...)
    message: "Potential SQL injection. Use parameterized queries instead."
    severity: ERROR
    languages: [python]
    metadata:
      owasp: "A03:2021 - Injection"
      cwe: "CWE-89"

  - id: python-command-injection
    patterns:
      - pattern-either:
          - pattern: os.system(...)
          - pattern: os.popen(...)
          - pattern: subprocess.call($CMD, shell=True, ...)
          - pattern: subprocess.run($CMD, shell=True, ...)
          - pattern: subprocess.Popen($CMD, shell=True, ...)
    message: "Potential command injection. Avoid shell=True and use list arguments."
    severity: ERROR
    languages: [python]
    metadata:
      owasp: "A03:2021 - Injection"
      cwe: "CWE-78"

  - id: python-code-injection
    patterns:
      - pattern-either:
          - pattern: eval(...)
          - pattern: exec(...)
          - pattern: compile(..., ..., "exec")
    message: "Dangerous use of eval/exec. Avoid executing dynamic code."
    severity: ERROR
    languages: [python]
    metadata:
      owasp: "A03:2021 - Injection"
      cwe: "CWE-94"

  # === DESERIALIZATION ===

  - id: python-unsafe-deserialization
    patterns:
      - pattern-either:
          - pattern: pickle.loads(...)
          - pattern: pickle.load(...)
          - pattern: yaml.load(..., Loader=yaml.Loader)
          - pattern: yaml.load(..., Loader=yaml.UnsafeLoader)
          - pattern: yaml.unsafe_load(...)
    message: "Unsafe deserialization. Use yaml.safe_load() or avoid pickle for untrusted data."
    severity: ERROR
    languages: [python]
    metadata:
      owasp: "A08:2021 - Software and Data Integrity Failures"
      cwe: "CWE-502"

  # === HARDCODED SECRETS ===

  - id: python-hardcoded-password-assignment
    pattern: |
      password = "..."
    message: "Hardcoded password detected. Load from environment variable."
    severity: ERROR
    languages: [python]
    metadata:
      cwe: "CWE-259"

  - id: python-hardcoded-api-key
    pattern-regex: "(api_key|apikey|api_secret|secret_key)\\s*=\\s*[\"'][a-zA-Z0-9_-]{16,}[\"']"
    message: "Potential hardcoded API key. Use environment variables instead."
    severity: WARNING
    languages: [python]
    metadata:
      owasp: "A07:2021 - Identification and Authentication Failures"
      cwe: "CWE-798"

  # === CRYPTOGRAPHIC ISSUES ===

  - id: python-weak-hash
    patterns:
      - pattern-either:
          - pattern: hashlib.md5(...)
          - pattern: hashlib.sha1(...)
    message: "Weak hash algorithm. Use SHA-256 or stronger for security purposes."
    severity: WARNING
    languages: [python]
    metadata:
      owasp: "A02:2021 - Cryptographic Failures"
      cwe: "CWE-328"

  - id: python-insecure-random
    patterns:
      - pattern-either:
          - pattern: random.random()
          - pattern: random.randint(...)
          - pattern: random.choice(...)
    message: "Insecure random for security purposes. Use secrets module instead."
    severity: INFO
    languages: [python]
    metadata:
      owasp: "A02:2021 - Cryptographic Failures"
      cwe: "CWE-330"

  # === NETWORK SECURITY ===

  - id: python-ssl-verification-disabled
    patterns:
      - pattern-either:
          - pattern: requests.get(..., verify=False, ...)
          - pattern: requests.post(..., verify=False, ...)
          - pattern: requests.put(..., verify=False, ...)
          - pattern: requests.delete(..., verify=False, ...)
          - pattern: httpx.get(..., verify=False, ...)
          - pattern: httpx.post(..., verify=False, ...)
          - pattern: httpx.Client(..., verify=False, ...)
          - pattern: httpx.AsyncClient(..., verify=False, ...)
    message: "SSL verification disabled. This allows man-in-the-middle attacks."
    severity: ERROR
    languages: [python]
    metadata:
      owasp: "A07:2021 - Identification and Authentication Failures"
      cwe: "CWE-295"

  # === PATH TRAVERSAL ===

  - id: python-path-traversal-open
    patterns:
      - pattern: open($USER_INPUT, ...)
      - metavariable-regex:
          metavariable: $USER_INPUT
          regex: '.*\+.*|.*\.format\(.*|f["\'].*'
    message: "Potential path traversal. Validate and sanitize file paths from user input."
    severity: WARNING
    languages: [python]
    metadata:
      owasp: "A01:2021 - Broken Access Control"
      cwe: "CWE-22"

  # === LOGGING ISSUES ===

  - id: python-sensitive-data-logging
    patterns:
      - pattern-either:
          - pattern: logger.$METHOD(..., password=..., ...)
          - pattern: logger.$METHOD(..., token=..., ...)
          - pattern: logger.$METHOD(..., secret=..., ...)
          - pattern: structlog.get_logger().$METHOD(..., password=..., ...)
          - pattern: structlog.get_logger().$METHOD(..., token=..., ...)
    message: "Potential sensitive data in logs. Mask or remove secrets before logging."
    severity: WARNING
    languages: [python]
    metadata:
      owasp: "A09:2021 - Security Logging and Monitoring Failures"
      cwe: "CWE-532"

  # === EXCEPTION HANDLING ===

  - id: python-bare-except
    pattern: |
      try:
          ...
      except:
          ...
    message: "Bare except catches all exceptions including KeyboardInterrupt. Catch specific exceptions."
    severity: WARNING
    languages: [python]
    metadata:
      cwe: "CWE-396"

  - id: python-exception-pass
    pattern: |
      try:
          ...
      except $E:
          pass
    message: "Silent exception handling. At minimum, log the error."
    severity: WARNING
    languages: [python]
    metadata:
      cwe: "CWE-390"

  # === ASYNC PATTERNS ===

  - id: python-blocking-in-async
    patterns:
      - pattern-inside: |
          async def $FUNC(...):
              ...
      - pattern-either:
          - pattern: time.sleep(...)
          - pattern: open(...)
    message: "Blocking call in async function. Use asyncio.sleep() or aiofiles for async I/O."
    severity: WARNING
    languages: [python]
    metadata:
      cwe: "CWE-400"

  # === FASTAPI SPECIFIC ===

  - id: fastapi-no-auth-decorator
    patterns:
      - pattern: |
          @$APP.$METHOD($PATH, ...)
          async def $FUNC(...):
              ...
      - pattern-not: |
          @$APP.$METHOD($PATH, ..., dependencies=[...], ...)
          async def $FUNC(...):
              ...
      - metavariable-regex:
          metavariable: $PATH
          regex: '.*/(admin|internal|private|settings).*'
    message: "Sensitive endpoint without explicit dependencies. Consider adding authentication."
    severity: INFO
    languages: [python]
    metadata:
      owasp: "A01:2021 - Broken Access Control"

  # === DEBUG/DEVELOPMENT CODE ===

  - id: python-debug-breakpoint
    patterns:
      - pattern-either:
          - pattern: breakpoint()
          - pattern: pdb.set_trace()
          - pattern: ipdb.set_trace()
    message: "Debug breakpoint in code. Remove before committing."
    severity: WARNING
    languages: [python]
    metadata:
      cwe: "CWE-489"

  - id: python-todo-fixme
    pattern-regex: '#\s*(TODO|FIXME|XXX|HACK):'
    message: "TODO/FIXME comment found. Address before merging if critical."
    severity: INFO
    languages: [python]
